### ISSUE TITLE
You don’t have vps servers m9

### ISSUE THREAD

**Issue by winsticks** [Mili-NT/BinBot#1346]
Again your python script won’t run 24/7, 
You’ll waste your own power that you pay for 🤣
Nice, I don’t need to waste any power
Cuz I get the servers for free
Up to 4 CPU’s 32 gigs ram
Or an F4s to fucking wipe your miserable GitHub rep ooo

**Comment by KuteKetX** [comment]
sir, this is in violation with ToS. If you refuse to stop posting issues we will file a complaint to Github. this section is not for arguments, thank you.
